"""PlatformIO pre-build script: gzip web/index.html into a PROGMEM header.

Serving the page gzipped (~2.5 KB instead of ~8 KB) keeps the response in a
single small allocation, which matters on a heap squeezed by BT Classic + WiFi.
"""
import gzip
import os

Import("env")  # noqa: F821

source = os.path.join(env["PROJECT_DIR"], "web", "index.html")  # noqa: F821
target = os.path.join(env["PROJECT_DIR"], "src", "hardware", "webpage.h")  # noqa: F821

with open(source, "rb") as f:
    data = gzip.compress(f.read(), 9)

lines = []
lines.append("// generated by build_web.py from web/index.html - do not edit")
lines.append("#pragma once")
lines.append("#include <pgmspace.h>")
lines.append(f"const uint32_t WEBPAGE_GZ_LEN = {len(data)};")
chunks = [", ".join(str(b) for b in data[i:i + 24]) for i in range(0, len(data), 24)]
lines.append("const uint8_t WEBPAGE_GZ[] PROGMEM = {\n" + ",\n".join(chunks) + "\n};")

content = "\n".join(lines) + "\n"

previous = None
if os.path.exists(target):
    with open(target, "r") as f:
        previous = f.read()

if content != previous:
    with open(target, "w") as f:
        f.write(content)
    print(f"build_web: embedded web/index.html ({len(data)} bytes gzipped)")
